name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000
  - secret: true
    name: adminKey
  - secret: true
    name: apiKey
  - secret: true
    name: certBase64
  - secret: true
    name: keyBase64
  - secret: true
    name: passphrase
